[codestyle]
indent_type='space' # 'tab' or 'space'
indent_width=2
template_file='~/atcoder-workspace/my_template.cpp'
workspace_dir='~/atcoder-workspace/'
lang='cpp' # Check README.md for the supported languages.

[postprocess]
exec_on_each_problem_dir='code main.cpp'

[etc]
download_without_login=false
parallel_download=false
save_no_session_cache=false
in_example_format="in_{}.txt"
out_example_format="out_{}.txt"
